from django.urls import path
from . import views

urlpatterns=[
    
    path('',views.home,name='home'),
    #path('upload/',views.upload,name='upload'),
    #path('chat2/',views.chat2,name='chat2'),
    #path('addcart',views.addcart,name='addcart'),
    path('send/',views.chat1,name='chat1'),
    path('1/',views.a1,name='1'),
    path('2/',views.a2,name='2'),
    path('3/',views.a3,name='3'),
    path('4/',views.a4,name='4'),
    path('5/',views.a5,name='5'),
    path('6/',views.a6,name='6'),
    path('7/',views.a7,name='7'),
    path('8/',views.a8,name='8'),
    path('9/',views.a9,name='9'),
    path('10/',views.a10,name='10'),
    path('11/',views.a11,name='11'),
    path('12/',views.a12,name='12'),
    path('13/',views.a13,name='13'),
    path('14/',views.a14,name='14'),
    path('15/',views.a15,name='15'),
    path('16/',views.a16,name='16'),
    path('17/',views.a17,name='17'),
    path('18/',views.a18,name='18'),
    path('19/',views.a19,name='19'),
    path('20/',views.a20,name='20'),
    path('21/',views.a21,name='21'),
    path('22/',views.a22,name='22'),
    path('23/',views.a23,name='23'),
    path('24/',views.a24,name='24'),
    path('25/',views.a25,name='25'),
    path('26/',views.a26,name='26'),
    path('27/',views.a27,name='27'),
    path('28/',views.a28,name='28'),
    path('29/',views.a29,name='29'),
    path('30/',views.a30,name='30'),
    path('chat1/',views.chat1,name='chat1'),
    path('search/',views.search,name='search'),
    path('check-out/',views.checkout,name='check-out'),
    path('faq/',views.faq,name='faq'),
    path('check-out/delete/',views.delete1,name='delete'),
    path('shopping-cart/',views.cart,name='shopping-cart'),
]
